// Date: 1/22/2017 3:52:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelvile_spirit extends ModelBase
{
  //fields
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head1;
    ModelRenderer cloak1;
    ModelRenderer cloak2;
    ModelRenderer cloak3;
    ModelRenderer cloak4;
    ModelRenderer spike1;
    ModelRenderer spike2;
    ModelRenderer spike3;
  
  public Modelvile_spirit()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      head2 = new ModelRenderer(this, 0, 16);
      head2.addBox(-3F, -3F, 0F, 6, 6, 5);
      head2.setRotationPoint(0F, 0F, -2F);
      head2.setTextureSize(128, 64);
      head2.mirror = true;
      setRotation(head2, 0F, 0F, 0F);
      head3 = new ModelRenderer(this, 0, 32);
      head3.addBox(-2F, -2F, 0F, 4, 4, 5);
      head3.setRotationPoint(0F, 0F, 2F);
      head3.setTextureSize(128, 64);
      head3.mirror = true;
      setRotation(head3, -0.3926991F, 0F, 0F);
      head1 = new ModelRenderer(this, 0, 0);
      head1.addBox(-4F, -4F, -4F, 8, 8, 5);
      head1.setRotationPoint(0F, 0F, -1F);
      head1.setTextureSize(128, 64);
      head1.mirror = true;
      setRotation(head1, 0.3926991F, 0F, 0F);
      cloak1 = new ModelRenderer(this, 32, 0);
      cloak1.addBox(-3.5F, 0F, -2F, 7, 12, 4);
      cloak1.setRotationPoint(0F, 3F, -1F);
      cloak1.setTextureSize(128, 64);
      cloak1.mirror = true;
      setRotation(cloak1, 0.1745329F, 0F, 0F);
      cloak2 = new ModelRenderer(this, 32, 16);
      cloak2.addBox(-1F, 0F, -2F, 2, 8, 4);
      cloak2.setRotationPoint(-2.5F, 14F, 1F);
      cloak2.setTextureSize(128, 64);
      cloak2.mirror = true;
      setRotation(cloak2, 0.1745329F, 0F, 0.1745329F);
      cloak3.mirror = true;
      cloak3 = new ModelRenderer(this, 32, 16);
      cloak3.addBox(-1F, 0F, -2F, 2, 8, 4);
      cloak3.setRotationPoint(2.5F, 14F, 1F);
      cloak3.setTextureSize(128, 64);
      cloak3.mirror = true;
      setRotation(cloak3, 0.1745329F, 0F, -0.1745329F);
      cloak3.mirror = false;
      cloak4 = new ModelRenderer(this, 32, 32);
      cloak4.addBox(-2F, 0F, -1F, 4, 8, 2);
      cloak4.setRotationPoint(0F, 13.5F, 2F);
      cloak4.setTextureSize(128, 64);
      cloak4.mirror = true;
      setRotation(cloak4, 0.3926991F, 0F, 0F);
      spike1 = new ModelRenderer(this, 32, 56);
      spike1.addBox(-1F, 0F, -1F, 2, 6, 2);
      spike1.setRotationPoint(2F, 6F, 1F);
      spike1.setTextureSize(128, 64);
      spike1.mirror = true;
      setRotation(spike1, 1.963495F, 0.2617994F, 0F);
      spike2 = new ModelRenderer(this, 32, 56);
      spike2.addBox(-1F, 0F, -1F, 2, 6, 2);
      spike2.setRotationPoint(-1.5F, 8F, 1F);
      spike2.setTextureSize(128, 64);
      spike2.mirror = true;
      setRotation(spike2, 1.832596F, -0.3926991F, 0F);
      spike3 = new ModelRenderer(this, 32, 56);
      spike3.addBox(-1F, 0F, -1F, 2, 6, 2);
      spike3.setRotationPoint(1.5F, 11F, 1F);
      spike3.setTextureSize(128, 64);
      spike3.mirror = true;
      setRotation(spike3, 1.308997F, 0.1308997F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head2.render(f5);
    head3.render(f5);
    head1.render(f5);
    cloak1.render(f5);
    cloak2.render(f5);
    cloak3.render(f5);
    cloak4.render(f5);
    spike1.render(f5);
    spike2.render(f5);
    spike3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
