package elucent.roots.ritual;

import elucent.roots.RegistryManager;
import elucent.roots.entity.EntityGreaterSprite;
import elucent.roots.entity.EntitySprite;
import elucent.roots.entity.EntitySpriteGuardian;
import elucent.roots.entity.EntitySpriteling;
import elucent.roots.ritual.rituals.*;
import elucent.roots.tileentity.TileEntityBrazier;
import net.minecraft.entity.monster.*;
import net.minecraft.entity.passive.*;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

import java.rmi.registry.Registry;
import java.util.ArrayList;

public class RitualManager {
	public static ArrayList<RitualBase> rituals = new ArrayList<RitualBase>();
	
	public static void init(){
		rituals.add(new RitualCrafting("staffCrafting", 205, 86, 0)
					.setResult(new ItemStack(RegistryManager.crystalStaff,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Blocks.COAL_BLOCK,1))
					.addIncense(new ItemStack(RegistryManager.darkOakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.STICK,1))
					.addIngredient(new ItemStack(Items.BLAZE_POWDER,1)));
		rituals.add(new RitualCrafting("lanceCrafting", 205, 86, 0)
				.setResult(new ItemStack(RegistryManager.spellweaverLance,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.logWildwood,1))
				.addIncense(new ItemStack(RegistryManager.darkOakTreeBark,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(Items.WOODEN_SWORD,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1)));
		rituals.add(new RitualCrafting("projectileStaffCrafting", 205, 86, 0)
				.setResult(new ItemStack(RegistryManager.projectileStaff,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.logWildwood,1))
				.addIncense(new ItemStack(RegistryManager.spruceTreeBark,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
				.addIngredient(new ItemStack(Items.GHAST_TEAR,1))
				.addIngredient(new ItemStack(Items.STICK,1))
				.addIngredient(new ItemStack(Items.DIAMOND,1)));
		rituals.add(new RitualCrafting("sylvanHoodCrafting", 62, 138, 62)
					.setResult(new ItemStack(RegistryManager.druidRobesHead,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(Items.GOLDEN_APPLE,1))
					.addIncense(new ItemStack(Blocks.RED_FLOWER,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.LEATHER_HELMET,1))
					.addIngredient(new ItemStack(Blocks.VINE,1)));
		rituals.add(new RitualCrafting("sylvanChestCrafting", 62, 138, 62)
					.setResult(new ItemStack(RegistryManager.druidRobesChest,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(Items.GOLDEN_APPLE,1))
					.addIncense(new ItemStack(Blocks.RED_FLOWER,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.LEATHER_CHESTPLATE,1))
					.addIngredient(new ItemStack(Blocks.VINE,1)));
		rituals.add(new RitualCrafting("sylvanLegsCrafting", 62, 138, 62)
					.setResult(new ItemStack(RegistryManager.druidRobesLegs,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(Items.GOLDEN_APPLE,1))
					.addIncense(new ItemStack(Blocks.RED_FLOWER,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.LEATHER_LEGGINGS,1))
					.addIngredient(new ItemStack(Blocks.VINE,1)));
		rituals.add(new RitualCrafting("sylvanBootsCrafting", 62, 138, 62)
					.setResult(new ItemStack(RegistryManager.druidRobesBoots,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.birchTreeBark,1))
					.addIncense(new ItemStack(Items.GOLDEN_APPLE,1))
					.addIncense(new ItemStack(Blocks.RED_FLOWER,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.LEATHER_BOOTS,1))
					.addIngredient(new ItemStack(Blocks.VINE,1)));
		rituals.add(new RitualCrafting("wildwoodHeadCrafting", 145, 115, 65)
					.setResult(new ItemStack(RegistryManager.druidArmorHead,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(Items.WHEAT,1))
					.addIncense(new ItemStack(Blocks.SAPLING,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.IRON_HELMET,1))
					.addIngredient(new ItemStack(Blocks.PLANKS,1,0)));
		rituals.add(new RitualCrafting("wildwoodChestCrafting", 145, 115, 65)
					.setResult(new ItemStack(RegistryManager.druidArmorChest,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(Items.WHEAT,1))
					.addIncense(new ItemStack(Blocks.SAPLING,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.IRON_CHESTPLATE,1))
					.addIngredient(new ItemStack(Blocks.PLANKS,1)));
		rituals.add(new RitualCrafting("wildwoodLegsCrafting", 145, 115, 65)
					.setResult(new ItemStack(RegistryManager.druidArmorLegs,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(Items.WHEAT,1))
					.addIncense(new ItemStack(Blocks.SAPLING,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.IRON_LEGGINGS,1))
					.addIngredient(new ItemStack(Blocks.PLANKS,1)));
		rituals.add(new RitualCrafting("wildwoodBootsCrafting", 145, 115, 65)
					.setResult(new ItemStack(RegistryManager.druidArmorBoots,1))
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
					.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(Items.WHEAT,1))
					.addIncense(new ItemStack(Blocks.SAPLING,1,0))
					.addIngredient(new ItemStack(Items.DIAMOND,1))
					.addIngredient(new ItemStack(Items.IRON_BOOTS,1))
					.addIngredient(new ItemStack(Blocks.PLANKS,1)));
		rituals.add(new RitualCrafting("acceleratorStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneAccelerator,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.jungleTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("aestheticStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneAesthetic,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1))
				.addIncense(new ItemStack(Items.DYE,1,1))
				.addIncense(new ItemStack(Items.DYE,1,4))
				.addIncense(new ItemStack(Items.DYE,1,2))
				.addIncense(new ItemStack(Items.DYE,1,15)));
		rituals.add(new RitualCrafting("entanglerStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneEntangler,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.oakTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("growerStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneGrower,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.birchTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("healerStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneHealer,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(Items.GHAST_TEAR,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("igniterStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneIgniter,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.acaciaTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("repulsorStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneRepulsor,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.spruceTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("vacuumStoneCrafting", 0, 105, 73)
				.setResult(new ItemStack(RegistryManager.standingStoneVacuum,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(RegistryManager.verdantSprig,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.WHEAT,1))
				.addIncense(new ItemStack(RegistryManager.darkOakTreeBark,1,0))
				.addIngredient(new ItemStack(RegistryManager.standingStoneT2,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1)));
		rituals.add(new RitualCrafting("amuletConservingCrafting", 222, 56, 255)
				.setResult(new ItemStack(RegistryManager.amuletConserving,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Blocks.WOOL,1))
				.addIncense(new ItemStack(Items.EGG,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Blocks.RED_FLOWER,1,5))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbol,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(RegistryManager.logWildwood,1)));
		rituals.add(new RitualCrafting("amuletDischargeCrafting", 242, 255, 42)
				.setResult(new ItemStack(RegistryManager.amuletDischarge,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.POISONOUS_POTATO,1))
				.addIncense(new ItemStack(Blocks.CACTUS,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Blocks.DOUBLE_PLANT,1,4))
				.addIngredient(new ItemStack(RegistryManager.runeStoneStairs,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneStairs,1)));
		rituals.add(new RitualCrafting("talismanHungerCrafting", 201, 133, 48)
				.setResult(new ItemStack(RegistryManager.talismanHunger,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.ROTTEN_FLESH,1))
				.addIncense(new ItemStack(Items.ENDER_EYE,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Blocks.SLIME_BLOCK,1))
				.addIngredient(new ItemStack(RegistryManager.logWildwood,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldSubstance,1))
				.addIngredient(new ItemStack(Items.STRING,1)));
		rituals.add(new RitualCrafting("talismanPursuitCrafting", 242, 61, 255)
				.setResult(new ItemStack(RegistryManager.talismanPursuit,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.FIRE_CHARGE,1))
				.addIncense(new ItemStack(Items.SPIDER_EYE,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Items.SUGAR,1))
				.addIngredient(new ItemStack(Items.BONE,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(Items.STRING,1)));
		rituals.add(new RitualCrafting("pixieStoneCrafting", 76, 230, 0)
				.setResult(new ItemStack(RegistryManager.pixieStone,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.FEATHER,1))
				.addIncense(new ItemStack(Blocks.YELLOW_FLOWER,1))
				.addIncense(new ItemStack(RegistryManager.infernalStem,1))
				.addIncense(new ItemStack(Blocks.WATERLILY,1))
				.addIngredient(new ItemStack(RegistryManager.runeStoneSymbolGlowing,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldSubstance,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1)));
		rituals.add(new RitualCrafting("ancientHourglassCrafting", 61, 219, 250)
				.setResult(new ItemStack(RegistryManager.ancientHourglass,1))
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.CHORUS_FRUIT,1))
				.addIncense(new ItemStack(Blocks.RED_FLOWER,1,8))
				.addIncense(new ItemStack(RegistryManager.dragonsEye,1))
				.addIncense(new ItemStack(Items.COAL,1,1))
				.addIngredient(new ItemStack(Blocks.GLASS,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldSubstance,1))
				.addIngredient(new ItemStack(Blocks.SAND,1,1)));
		rituals.add(new RitualCrafting("livingPickaxeCrafting", 146, 214, 43)
					.setResult(new ItemStack(RegistryManager.livingPickaxe,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIngredient(new ItemStack(Items.WOODEN_PICKAXE,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1))
					.addIngredient(new ItemStack(Items.GOLD_INGOT,1)));
		rituals.add(new RitualCrafting("livingAxeCrafting", 146, 214, 43)
					.setResult(new ItemStack(RegistryManager.livingAxe,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIngredient(new ItemStack(Items.WOODEN_AXE,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1))
					.addIngredient(new ItemStack(Items.GOLD_INGOT,1)));
		rituals.add(new RitualCrafting("livingSwordCrafting", 146, 214, 43)
					.setResult(new ItemStack(RegistryManager.livingSword,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIngredient(new ItemStack(Items.WOODEN_SWORD,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1))
					.addIngredient(new ItemStack(Items.GOLD_INGOT,1)));
		rituals.add(new RitualCrafting("livingHoeCrafting", 146, 214, 43)
					.setResult(new ItemStack(RegistryManager.livingHoe,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIngredient(new ItemStack(Items.WOODEN_HOE,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1))
					.addIngredient(new ItemStack(Items.GOLD_INGOT,1)));
		rituals.add(new RitualCrafting("livingShovelCrafting", 146, 214, 43)
					.setResult(new ItemStack(RegistryManager.livingShovel,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
					.addIngredient(new ItemStack(Items.WOODEN_SHOVEL,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1))
					.addIngredient(new ItemStack(Items.GOLD_INGOT,1)));
		rituals.add(new RitualCauseRain("causerain", 23, 0, 138)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Blocks.VINE,1))
					.addIncense(new ItemStack(RegistryManager.oldRoot,1))
					.addIngredient(new ItemStack(Blocks.WATERLILY,1)));
		rituals.add(new RitualBanishRain("banishrain", 204, 159, 35)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Blocks.VINE,1))
					.addIncense(new ItemStack(RegistryManager.oldRoot,1))
					.addIngredient(new ItemStack(Items.WHEAT,1)));
		rituals.add(new RitualStaffImbuer()
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIngredient(new ItemStack(RegistryManager.crystalStaff,1))
					.addIngredient(new ItemStack(RegistryManager.verdantSprig,1)));
		rituals.add(new RitualLanceImbuer()
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addIngredient(new ItemStack(RegistryManager.spellweaverLance,1))
				.addIngredient(new ItemStack(RegistryManager.verdantSprig,1)));
		rituals.add(new RitualProjectileStaffImbuer()
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addIngredient(new ItemStack(RegistryManager.projectileStaff,1))
				.addIngredient(new ItemStack(RegistryManager.verdantSprig,1)));
		rituals.add(new RitualSummoning("cowSummoning",199,105,193)
					.setResult(EntityCow.class)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Items.WHEAT_SEEDS,1))
					.addIncense(new ItemStack(Items.NETHER_WART,1))
					.addIngredient(new ItemStack(Items.BEEF,1))
					.addIngredient(new ItemStack(Items.LEATHER,1))
					.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSummoning("pigSummoning",199,105,193)
					.setResult(EntityPig.class)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Items.WHEAT_SEEDS,1))
					.addIncense(new ItemStack(Items.NETHER_WART,1))
					.addIngredient(new ItemStack(Items.PORKCHOP,1))
					.addIngredient(new ItemStack(Items.PORKCHOP,1))
					.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSummoning("sheepSummoning",199,105,193)
					.setResult(EntitySheep.class)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Items.WHEAT_SEEDS,1))
					.addIncense(new ItemStack(Items.NETHER_WART,1))
					.addIngredient(new ItemStack(Items.MUTTON,1))
					.addIngredient(new ItemStack(Blocks.WOOL,1))
					.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSummoning("chickenSummoning",199,105,193)
					.setResult(EntityChicken.class)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Items.WHEAT_SEEDS,1))
					.addIncense(new ItemStack(Items.NETHER_WART,1))
					.addIngredient(new ItemStack(Items.CHICKEN,1))
					.addIngredient(new ItemStack(Items.FEATHER,1))
					.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSummoning("rabbitSummoning",199,105,193)
					.setResult(EntityRabbit.class)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
					.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
					.addIncense(new ItemStack(Items.WHEAT_SEEDS,1))
					.addIncense(new ItemStack(Items.NETHER_WART,1))
					.addIngredient(new ItemStack(Items.RABBIT,1))
					.addIngredient(new ItemStack(Items.RABBIT_HIDE,1))
					.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSummoning("zombieSummoning",58,2,84)
				.setResult(EntityZombie.class)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.COAL,1))
				.addIncense(new ItemStack(Items.NETHER_WART,1))
				.addIngredient(new ItemStack(Items.ROTTEN_FLESH,1))
				.addIngredient(new ItemStack(Items.ROTTEN_FLESH,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
	rituals.add(new RitualSummoning("skeletonSummoning",58,2,84)
				.setResult(EntitySkeleton.class)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.COAL,1))
				.addIncense(new ItemStack(Items.NETHER_WART,1))
				.addIngredient(new ItemStack(Items.ARROW,1))
				.addIngredient(new ItemStack(Items.BONE,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
	rituals.add(new RitualSummoning("spiderSummoning",58,2,84)
				.setResult(EntitySpider.class)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.COAL,1))
				.addIncense(new ItemStack(Items.NETHER_WART,1))
				.addIngredient(new ItemStack(Items.STRING,1))
				.addIngredient(new ItemStack(Items.SPIDER_EYE,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
	rituals.add(new RitualSummoning("caveSpiderSummoning",58,2,84)
			.setResult(EntityCaveSpider.class)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
			.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
			.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
			.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
			.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
			.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
			.addIncense(new ItemStack(Items.COAL,1))
			.addIncense(new ItemStack(Items.NETHER_WART,1))
			.addIngredient(new ItemStack(Items.STRING,1))
			.addIngredient(new ItemStack(Items.FERMENTED_SPIDER_EYE,1))
			.addIngredient(new ItemStack(Items.BONE,1)));
	rituals.add(new RitualSummoning("slimeSummoning",58,2,84)
			.setResult(EntitySlime.class)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
			.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
			.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
			.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
			.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
			.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
			.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
			.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
			.addIncense(new ItemStack(Items.COAL,1))
			.addIncense(new ItemStack(Items.NETHER_WART,1))
			.addIngredient(new ItemStack(Items.SLIME_BALL,1))
			.addIngredient(new ItemStack(Items.SLIME_BALL,1))
			.addIngredient(new ItemStack(Items.SLIME_BALL,1)));
	rituals.add(new RitualSummoning("creeperSummoning",58,2,84)
				.setResult(EntityCreeper.class)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.COAL,1))
				.addIncense(new ItemStack(Items.NETHER_WART,1))
				.addIngredient(new ItemStack(Items.GUNPOWDER,1))
				.addIngredient(new ItemStack(Items.GUNPOWDER,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
	rituals.add(new RitualSummoning("endermanSummoning",58,2,84)
				.setResult(EntityEnderman.class)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.COAL,1))
				.addIncense(new ItemStack(Items.NETHER_WART,1))
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualSacrifice("sacrifice", 94, 9, 56)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIncense(new ItemStack(Items.BLAZE_POWDER,1))
				.addIncense(new ItemStack(RegistryManager.darkOakTreeBark,1,0))
				.addIngredient(new ItemStack(Items.FLINT,1))
				.addIngredient(new ItemStack(Items.IRON_SWORD,1))
				.addIngredient(new ItemStack(Items.BONE,1)));
		rituals.add(new RitualTimeShift("timeshift", 240, 245, 88, 252, 162, 35)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addIngredient(new ItemStack(Items.CLOCK))
				.addIngredient(new ItemStack(Items.IRON_INGOT)));
		rituals.add(new RitualWildwood("wildwood", 19, 84, 48)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addIncense(new ItemStack(RegistryManager.oakTreeBark,1))
				.addIncense(new ItemStack(RegistryManager.spruceTreeBark,1))
				.addIncense(new ItemStack(RegistryManager.jungleTreeBark,1))
				.addIncense(new ItemStack(RegistryManager.acaciaTreeBark,1))
				.addIngredient(new ItemStack(Blocks.VINE,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1))
				.addIngredient(new ItemStack(RegistryManager.verdantSprig,1)));
		/*rituals.add(new RitualPowerGiver("restoration", 139, 22, 40)
				.setPower(new RitualPowerRestoration())
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.MILK_BUCKET))
				.addIngredient(new ItemStack(Items.FEATHER))
				.addIngredient(new ItemStack(RegistryManager.itemCharmRestoration)));
		rituals.add(new RitualPowerGiver("illusion", 139, 22, 40)
				.setPower(new RitualPowerIllusion())
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.ENDER_PEARL))
				.addIngredient(new ItemStack(RegistryManager.itemCharmIllusion)));
		rituals.add(new RitualPowerGiver("conjuration", 139, 22, 40)
				.setPower(new RitualPowerConjuration())
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.APPLE))
				.addIngredient(new ItemStack(RegistryManager.itemCharmConjuration)));
		rituals.add(new RitualPowerGiver("evocation", 139, 22, 40)
				.setPower(new RitualPowerEvocation())
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(RegistryManager.itemCharmEvocation)));*/
		rituals.add(new RitualSpiritSummoning("spritelingSummoning",107,255,28)
				.init(EntitySpriteling.class,4,false)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(Items.REDSTONE,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1)));
		rituals.add(new RitualSpiritSummoning("spriteSummoning",107,255,28)
				.init(EntitySprite.class,6,false)
				.setSpiritCosts(1, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(Items.GLOWSTONE_DUST,1)));
		rituals.add(new RitualSpiritSummoning("greaterSpriteSummoning",107,255,28)
				.init(EntityGreaterSprite.class,8,false)
				.setSpiritCosts(2, 1, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.ENDER_PEARL,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(Items.BLAZE_POWDER,1)));
		rituals.add(new RitualSpiritSummoning("spriteGuardianSummoning",107,255,28)
				.init(EntitySpriteGuardian.class,12,true)
				.setSpiritCosts(4, 2, 2)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, -3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, -3, 0, 0)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, 3)
				.addBlock(RegistryManager.standingStoneT1, 0, 0, -3)
				.addBlock(RegistryManager.standingStoneT2, 5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, -5, 1, 0)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, 5)
				.addBlock(RegistryManager.standingStoneT2, 0, 1, -5)
				.addIngredient(new ItemStack(Items.DIAMOND,1))
				.addIngredient(new ItemStack(RegistryManager.otherworldLeaf,1))
				.addIngredient(new ItemStack(Items.GHAST_TEAR,1)));


	}
	
	public static RitualBase getRitualFromName(String name){
		for (int i = 0; i < rituals.size(); i ++){
			if (rituals.get(i).name == name){
				return rituals.get(i);
			}
		}
		return null;
	}
	
	public static ArrayList<ItemStack> getIncenses(World world, BlockPos pos){
		ArrayList<ItemStack> test = new ArrayList<ItemStack>();
		for (int i = -4; i < 5; i ++){
			for (int j = -4; j < 5; j ++){
				if (world.getBlockState(pos.add(i,0,j)).getBlock() == RegistryManager.brazier){
					if (world.getTileEntity(pos.add(i,0,j)) != null){
						TileEntityBrazier teb = (TileEntityBrazier)world.getTileEntity(pos.add(i,0,j));
						if (teb.burning){
							test.add(teb.heldItem);
						}
					}
				}
			}
		}
		return test;
	}
}
